### ISSUE TITLE
Incompatible with Lethal Things Mod

### ISSUE THREAD

**Issue by Kayden21** [Theronguard/Emergency-Dice#1]
Hey it seems like the dice cannot be bought when the lethal things mod is downloaded because it thinks I am trying to buy the emergency flare. I tried typing in just dice and it did not work so I cant buy it. Seems like a pretty simple fix to just make typing in dice also buy the item. Other than that I have not really had any problems.

**Comment by BAHEK-BOP** [comment]
[Theronguard](https://github.com/Theronguard) I basically wanted to write with the same problem

**Comment by Theronguard** [comment]
I barely had time to analyze how terminals work and write code, but you could try buying the die by typing in "emergency-die" as the lethallib changes spaces into "-".  Please tell me if it works as I can't test it with lethal things right now.

**Comment by MadsLundJensen** [comment]
> I barely had time to analyze how terminals work and write code, but you could try buying the die by typing in "emergency-die" as the lethallib changes spaces into "-". Please let me know if it works as I can't test it with lethal things right now.

That does not work, unfortunately.

**Comment by Theronguard** [comment]
Added some aliases in the last commit.
Try buying it with "emergencydie", "dice", "die" or "edie" and let me know if it solved the problem for you.

**Comment by MadsLundJensen** [comment]
> Added some aliases in the last commit. Try buying it with "emergencydie", "dice", "die" or "edie" and let me know if it solved the problem for you.

Will try later, thanks!

**Comment by Warkanam** [comment]
It looks fixed to me, it worked very well.

**Comment by Theronguard** [comment]
> It looks fixed to me, it worked very well.

Thanks for the confirmation! Closing.
