### ISSUE TITLE
Non-hosts sometimes can not use the dice.

### ISSUE THREAD

**Issue by Ascensus-31** [Theronguard/Emergency-Dice#10]
this is my pack code: 018de5e0-273b-b401-9900-29db3b7a0017
I test 3 times with my two friends, everytime when the game started, they can not use the dice.
First time, we skip to second day and it became normal. non-hosts can use all dice.
Second time, non-hosts didnt skip to second day but just changed the type of dice from The Saint to The Sacrificer, and it became normal. 
Third time, non-hosts try to use the saint for 7or 8 times, it doesnt work. and we didnt continue.
non-hosts can't use the dice just like: The animation will play and explode, but it will not take effect and there will be no on-screen tips.
AND after the first time the non-hosts can use the dice, they can use it every time.(The first time here is not the first time mentioned earlier)

I don't know if there have some conficts in my modpack?

**Comment by Asc3nt** [comment]
btw you can remove the "SweetFox-Lethal_Company_Simplified_Chinese_Localization-1.7.8" mod, because i don't know whether the config will sycn to you, that localization mod should change some configs or it will not appear the on-screen tips.

**Comment by Asc3nt** [comment]
And found another bug, when non-hosts use Rusty, it cant spawn scraps, even hit 6.

**Comment by Asc3nt** [comment]
Hey i test just tested only install your mod, and i found that it's not mods conflicts. All the bugs I mentioned above appeared in non-hosts rolled without any other mods.

**Comment by Theronguard** [comment]
Hey, sorry for the delay. Update to the latest version of the game (V50) and update the mod. Make sure to remove the emergency dice config file to let it regenerate. Could stem from similar issue as #13 . If you can, send me the console log after this bug happens.

**Comment by Ascensus-31** [comment]
Glad to receive your latest update, I'v been consistently playing with your mod. I tested it with multiple players and it runs perfectly now. I will let you know if I encounter any other bugs.
