### ISSUE TITLE
impossible to use dices

### ISSUE THREAD

**Issue by Gravitron7** [Theronguard/Emergency-Dice#5]
whether it's the host or the players, the dice don't work, they throw their animation, like, they spin, make an explosion but there's no other effect, we tried with the emergency dice about thirty times and nothing more, if we had a little smiley on the screen

**Comment by Gravitron7** [comment]
i'll do when im home ican't actually

**Comment by Gravitron7** [comment]
so i tried the lastest version, the 1.1.12 and all the dice are good host and players can now use them thanks you very much, its a really cool mod :D

**Comment by Theronguard** [comment]
Thanks for the confirmation, and for nice words. Closing #5 and #4 as they seem to be duplicate.
