### ISSUE TITLE
[Question] if fake fire exit are effected, is that can compatible with Mimics mod?

### ISSUE THREAD

**Issue by CoolLKKPS** [Theronguard/Emergency-Dice#6]
also pls add "host config will sync to client" in mod description if this mod really can do that

**Comment by Theronguard** [comment]
> also pls add "host config will sync to client" in mod description if this mod really can do that

Will do in the next commit.

From my understanding of the mimics mod, this effect shouldn't cause any problems as I didnt patch any existing methods to make it. Another effect - "Fire exit block" might block fire exits that are mimics (strong emphasis on Might), and when you try to open a mimiced door it may or may not activate, but I dont think thats a huge problem as this would only happen when the effect is active. You can always turn them off in the config if they cause problems, but I think they should be fine.
