### ISSUE TITLE
Suggestion: Add a catch-all and/or custom moon config option for modded moons

### ISSUE THREAD

**Issue by Xarathoss** [Theronguard/Emergency-Dice#9]
Heya!

Our group has been playing with this mod and we think it's really fun! however we were confused why dice eventually stopped appearing, and it turned out that that was because, from what I can tell, they're only set to spawn on vanilla moons. It'd be nice if there was a fallback config option for every other moon not explicitly mentioned in the config, as we typically tend to stop going to vanilla moons after the first 1 or 2 visits to the company. I've seen other mods utilize a string field along the lines of `Rend@15, Titan@20, Orion@25` etc. to handle weights on individual moons, such as [this one](https://github.com/Badhamknibbs/SCPCB_DunGen_LC/blob/main/SCPCBDunGen/Plugin.cs#L142), which would work nicely alongside the fallback as well for moons that aren't explicitly covered by the config.

Also, on an unrelated note, me and my wife have gotten into modding very recently, and I wanted to say we very much appreciate you making this mod open source. So far it's been a great resource to learn from just because it does a bit of everything, and since patching methods is not as intuitive as writing straight source code it's really helpful to have a functional example to learn from!

Keep up the good work :)

**Comment by Theronguard** [comment]
I will try to add this at the end of the week. Thanks for nice words and providing an example - this will speed up my work. Hope you don't catch any bad practices from my code, as I'm only a C# Junior :p

**Comment by Xarathoss** [comment]
Hey, if it works it works, right? I haven't touched OOP in years so you're way ahead of me haha

And sweet, looking forward to it!

**Comment by ProjectBots** [comment]
How is it coming along?

**Comment by Theronguard** [comment]
Sorry for the long wait. I added a "default" rarity option to the config, so all of the non standard moons will just get the rarity from this value. Thanks for the suggestion and the patience
